### ISSUE TITLE
Comparison of ablation experiments  chart

### ISSUE THREAD

**Issue by zhangyuanyuan123456** [TianhongDai/esil-hindsight#4]
Hello! I'm very interested in your research! I want to reproduce your paper, the result is very good, but can you provide the code of the comparison chart in your paper? As shown in Figures 4 and 5. I don't know how to achieve this! thank you

**Comment by zhangyuanyuan123456** [comment]
![~Z~$B%3 BL@(5~ IA)U HV](https://user-images.githubusercontent.com/87747605/126735381-5146d338-9018-4ab1-bcc1-eb955cf2625a.png)
Like this picture, can you teach me how to do it? thank you!

**Comment by zhangyuanyuan123456** [comment]
![~Z~$B%3 BL@(5~ IA)U HV](https://user-images.githubusercontent.com/87747605/126735522-1408502b-9359-445d-8554-87c370b56ae0.png)


Like this picture, can you teach me how to do it? thank you!

**Comment by TianhongDai** [comment]
@zhangyuanyuan123456 Sorry for responding late, do you mean the code for drawing the plots? I will upload the code for drawing the plots after several hours.

**Comment by TianhongDai** [comment]
@zhangyuanyuan123456 I have uploaded the script to plot curves in `plot_curves.py`. In order to get the log info, you could try the following command:
```
mpirun -np 16 python -u train.py --env-name='FetchPush-v1' --adaptive-beta --display-interval=1 --total-frames=2500000 2>&1 | tee seed_1.log
```
Alternatively, you can also use `logging` package in python to record the log information. Furthermore, you need to install `seaborn` package to make sure you can run the `plot_curves.py`.
